### ISSUE TITLE
Changes after updating to 2.5?

### ISSUE THREAD

**Issue by jsibley2** [cloudyr/limer#10]
I updated to limesurvey v2.5 today and it appears that the url for remotecontrol has changed. It appears to be at /admin/remotecontrol now.

That is fine, but when I try to use that in options() it returns NULL and doesn't allow a connection. Is there something else I need to do on my end?

Thanks for a really useful interface, in any case.

**Comment by andrewheiss** [comment]
Did the update change the URL rewriting settings? Can you access it via http://host.name/index.php?r=admin/remotecontrol

**Comment by jsibley2** [comment]
admin/remotecontrol works

index.php?r=admin/remotecontrol

takes me to a page that says Surveys list on the upper left and has the 
contact info for further assistance on the bottom.

Thanks.

On 6/6/2016 3:51 PM, Andrew Heiss wrote:
>
> Did the update change the URL rewriting settings? Can you access it 
> via http://host.name/index.php?r=admin/remotecontrol
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/cloudyr/limer/issues/10#issuecomment-224068290>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGRbOaG1T3Ix5ml7SDsvxQMCJ9U780pjks5qJHpTgaJpZM4IvO7w>.
>

-- 
*Executive and Personal Coaching and Psychotherapy*
/Helping people to change when change is difficult/
in English, French, Spanish, Portuguese, and German
www.jonathansibley.net <http://www.jonathansibley.net>
973-337-6017 (office)

**Comment by andrewheiss** [comment]
I'm running 2.5 as well (but with URL rewriting turned off), and the API connects.

Are you familiar with Docker? Try installing this image, creating a sample survey, and connecting to it: https://hub.docker.com/r/crramirez/limesurvey/

**Comment by jsibley2** [comment]
I'm not sure if it makes a difference, but I am running my surveys using 
Limeservice. Could that make a difference?

Perhaps they are doing something that causes the URL not to work in this 
case?

Would you like me to contact them?

Thanks.


On 6/6/2016 4:10 PM, Andrew Heiss wrote:
>
> I'm running 2.5 as well (but with URL rewriting turned off), and the 
> API connects.
>
> Are you familiar with Docker? Try installing this image, creating a 
> sample survey, and connecting to it: 
> https://hub.docker.com/r/crramirez/limesurvey/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/cloudyr/limer/issues/10#issuecomment-224073270>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGRbOR7u0WAlnMHHd8eTwhMQh2fbG5bfks5qJH7BgaJpZM4IvO7w>.
>

-- 
*Executive and Personal Coaching and Psychotherapy*
/Helping people to change when change is difficult/
in English, French, Spanish, Portuguese, and German
www.jonathansibley.net <http://www.jonathansibley.net>
973-337-6017 (office)

**Comment by andrewheiss** [comment]
Hrm. Maybe something is improperly configured with your survey? This runs correctly for me (connecting to their demo server):

```r
library(limer)

options(lime_api = 'https://lsdemo.limequery.com/admin/remotecontrol')
options(lime_username = 'limedemo')
options(lime_password = 'demo')

get_session_key()
```

**Comment by jsibley2** [comment]
User error. Sorry. I forgot to add lime_api =

Working fine now. Thanks!


On 6/6/2016 4:49 PM, Andrew Heiss wrote:
>
> Hrm. Maybe something is improperly configured with your survey? This 
> runs correctly for me (connecting to their demo server):
>
> library(limer)
>
> options(lime_api  =  'https://lsdemo.limequery.com/admin/remotecontrol')
> options(lime_username  =  'limedemo')
> options(lime_password  =  'demo')
>
> get_session_key()
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/cloudyr/limer/issues/10#issuecomment-224083870>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGRbOZSQr2f4_asdzRCJChc8lniBdtyAks5qJIfygaJpZM4IvO7w>.
>

-- 
*Executive and Personal Coaching and Psychotherapy*
/Helping people to change when change is difficult/
in English, French, Spanish, Portuguese, and German
www.jonathansibley.net <http://www.jonathansibley.net>
973-337-6017 (office)
