### ISSUE TITLE
Are there any recent changes for get_responses and export_responses to work now?

### ISSUE THREAD

**Issue by jsibley2** [cloudyr/limer#38]
When I use get_responses from limer now, the first line of variable names seems to be delimited by "." and the rest of the data seems to be delimited by ";".

If I use call_limer with "export responses" and base64_to_df to create a dataframe, I'm getting 1 variable rather than multiple variables for each responses (I'm guessing, for the same reason as above.

Is there something I need to be doing differently now? I don't think that I had tried this until updating from an older version of limesurvey and remotecontrol.

Thanks for any help.

**Comment by jemus42** [comment]
I just updated my LimeSurvey install and yep, now I regret it. 
Looks like some formatting changed, so we'll either need to clean up ourselves or wait for this package to update.

**Comment by jemus42** [comment]
Turns out the fix was pretty easy: https://github.com/cloudyr/limer/pull/39

**Comment by andrewheiss** [comment]
I merged in the fix, but it's failing CI building for some reason…
