### ISSUE TITLE
Log in not working

### ISSUE THREAD

**Issue by jorgesinval** [cloudyr/limer#54]
When I use the function `get_session_key` after defining the username, password, and API, I get the following error:

```
Error: Argument 'txt' must be a JSON string, URL or file.
```

Any thoughts?

**Comment by SebastianHuter** [comment]
i have the same issue, trying to access a LimeSurvey 4.1.15 installation.
It seems like an error from the function jsonlite::toJSON within get_session_key and that it somehow doesn't get or like the lime_api URL from the options. But I couldn't really solve it yet. Any success?

**Comment by jemus42** [comment]
I have not tried LimeSurvey 4.x yet, but I have experienced the given error message temporarily, sometimes over the course of one or two days. If all LimeSurvey settings are defined correctly, it may legitimately be a "just wait a bit and try again" issue if you're lucky. 

(I could never figure out what caused the issue, sorry)

**Comment by akuehn** [comment]
Set RPC-Interface to `JSON-RPC`

**Comment by SebastianHuter** [comment]
that did the trick, thank you!
