### ISSUE TITLE
Fetching all available data (including incomplete)

### ISSUE THREAD

**Issue by mkalz** [cloudyr/limer#64]
Hi,

thanks so much for the Limer package which makes data fetching so easy with Limesurvey. I would like to fetch not only complete responses but all responses. How is this possible?

Thanks!

**Comment by forstem6** [comment]
Hi mkalz,

this should work by specifying the completion status in the `get_responses` call.
Something like this: `raw_dat <- get_responses(<yourSurveyID>,  sCompletionStatus = "all")`

Just a few words on the rationale. `get_responses()` is a convenient way to use the export_responses method of the LimeSurvey API with specified default values (see the function help for the defaults). Unfortunately, the help is a bit sparse with info about this.

**Comment by mkalz** [comment]
Great - thanks so much!
