### ISSUE TITLE
list_participants returns a data.frame with a column that is a data.frame

### ISSUE THREAD

**Issue by andrewheiss** [cloudyr/limer#9]
Received via e-mail:

---

Is this intended behaviour?

``` r
> req2 <- call_limer("list_participants", list(971744))
> names(req2)
[1] "tid"              "token"            "participant_info"
> get_session_key(password=LSPASSWORD,username = LSUSER)
[1] "xwi3uhr5kf4wapmv255i8k8s5gkcvhgr"
> req2 <- call_limer("list_participants", list(971744))
> names(req2)
[1] "tid"              "token"            "participant_info"
> class(req2$participant_info)
[1] "data.frame"
> names(req2$participant_info)
[1] "firstname" "lastname"  "email"
```

So list_participants returns a dataframe of 3 columns, one of which is a dataframe on itself.

**Comment by jsibley2** [comment]
As mentioned in another issue, get_participants seems not to be working.

Using call_limer seems to work, but how do we ask for attributes to be included in the results?

Thanks!

**Comment by tammoterhark** [comment]
@jsibley2 : did you manage to find out? I am facing the same thing... Would love to get some direction.

**Comment by Jan-E** [comment]
> So list_participants returns a dataframe of 3 columns, one of which is a dataframe on itself.

This is intended behaviour by the designers of LS:
https://github.com/LimeSurvey/LimeSurvey/blob/master/application/helpers/remotecontrol/remotecontrol_handle.php#L1856

**Comment by Jan-E** [comment]
> ... how do we ask for attributes to be included in the results?

That is another issue.

`participants<-get_participants(693329,iStart=0,iLimit=1007,bUnused=TRUE,aAttributes=c('attribute_1','attribute_2'))
`
is the way to do that.

**Comment by andrewheiss** [comment]
Closing this since it's reflects the API's expected behavior (and it's clearer now thanks to #14)
